package com.howard.project.util

const val REQUEST_CODE_ALL_PERMISSION = 1001
const val REQUEST_CODE_CAMERA = 1002
const val REQUEST_CODE_BLUETOOTH = 1003
const val REQUEST_CODE_LOCATION = 1004
const val REQUEST_CODE_FILE = 1005
const val REQUEST_CODE_READ_FILE = 1006
const val REQUEST_CODE_NOTIFICATION = 1007
const val REQUEST_CODE_PHONE_STATE = 1008
const val REQUEST_CODE_QR_CODE_ACTIVITY = 0x10

//shared preference file
const val localPrefFileName = "localPref"
const val localeLanguagePrefKey = "localeLanguage"
const val localeCountryPrefKey = "localeCountry"

//notification type
const val NOTIFICATION_TYPE_TEST = "NOTIFICATION_TYPE_TEST"

//bundle
const val BUNDLE_FCM_NOTIFICATION_TYPE = "BUNDLE_FCM_NOTIFICATION_TYPE"
const val BUNDLE_FCM_DATA = "BUNDLE_FCM_DATA"
const val BUNDLE_CAMERA_SCANNER_RESULT = "BUNDLE_CAMERA_SCANNER_RESULT"
const val BUNDLE_SELECTED_IMAGE_DATA = "BUNDLE_SELECTED_IMAGE_DATA"
const val BUNDLE_SELECT_GALLERY_IMAGE_RESULT = "BUNDLE_SELECT_GALLERY_IMAGE_RESULT"
const val BUNDLE_READ_NFC_RESULT = "BUNDLE_READ_NFC_RESULT"