package com.howard.project.util

const val REQUEST_CODE_ALL_PERMISSION = 1001
const val REQUEST_CODE_CAMERA = 1002
const val REQUEST_CODE_BLUETOOTH = 1003
const val REQUEST_CODE_LOCATION = 1004
const val REQUEST_CODE_FILE = 1005
const val REQUEST_CODE_READ_FILE = 1006
const val REQUEST_CODE_NOTIFICATION = 1007
const val REQUEST_CODE_PHONE_STATE = 1008
const val REQUEST_CODE_QR_CODE_ACTIVITY = 0x10

//shared preference file
const val localPrefFileName = "localPref"
const val localeLanguagePrefKey = "localeLanguage"
const val localeCountryPrefKey = "localeCountry"

//notification type
const val NOTIFICATION_TYPE_TEST = "NOTIFICATION_TYPE_TEST"

//bundle
const val BUNDLE_FCM_NOTIFICATION_TYPE = "BUNDLE_FCM_NOTIFICATION_TYPE"
const val BUNDLE_FCM_DATA = "BUNDLE_FCM_DATA"
const val BUNDLE_CAMERA_SCANNER_RESULT = "BUNDLE_CAMERA_SCANNER_RESULT"
const val BUNDLE_SELECTED_IMAGE_DATA = "BUNDLE_SELECTED_IMAGE_DATA"
const val BUNDLE_SELECT_GALLERY_IMAGE_RESULT = "BUNDLE_SELECT_GALLERY_IMAGE_RESULT"
const val BUNDLE_READ_NFC_RESULT = "BUNDLE_READ_NFC_RESULT"

//APDU command response code
const val APDU_RESPONSE_CODE_OK = "9000"
const val APDU_RESPONSE_CODE_WARNING_A = "62"
const val APDU_RESPONSE_CODE_WARNING_B = "63"
const val APDU_RESPONSE_CODE_ERROR_A = "69"
const val APDU_RESPONSE_CODE_ERROR_B = "6A"

const val APDU_COMMAND_INIT = "00A404000E315041592E5359532E444446303100"
const val APDU_COMMAND_READ_EF1_RECORD1 = "00B2010C00"
const val APDU_COMMAND_READ_EF1_RECORD2 = "00B2020C00"
const val APDU_COMMAND_READ_EF2_RECORD1 = "00B2011400"
const val APDU_COMMAND_GPO_WITHOUT_PDOL = "80A8000002830000"
